server:
  http:
    addr: 0.0.0.0:8602
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9602
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123123@tcp(127.0.0.1:3306)/test_user?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
